<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Cluster analysis of potato cultivars | Nutrient Diagnosis Of Potato</title>
  <meta name="description" content="This is a example of using the bookdown package to write a book that describ the statistical computations of my PhD Project, for publication on Github. The output format choosed is bookdown::gitbook. Next features are set out for after (bibliography and links)." />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Cluster analysis of potato cultivars | Nutrient Diagnosis Of Potato" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a example of using the bookdown package to write a book that describ the statistical computations of my PhD Project, for publication on Github. The output format choosed is bookdown::gitbook. Next features are set out for after (bibliography and links)." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Cluster analysis of potato cultivars | Nutrient Diagnosis Of Potato" />
  
  <meta name="twitter:description" content="This is a example of using the bookdown package to write a book that describ the statistical computations of my PhD Project, for publication on Github. The output format choosed is bookdown::gitbook. Next features are set out for after (bibliography and links)." />
  

<meta name="author" content="zcoulibali" />


<meta name="date" content="2019-06-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html">
<link rel="next" href="Chapter-Modeling.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Data processing</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#Objective"><i class="fa fa-check"></i><b>1.1</b> Objective</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#useful-libraries-for-data-handling"><i class="fa fa-check"></i><b>1.2</b> Useful libraries for data handling</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#quebec-potato-data-set"><i class="fa fa-check"></i><b>1.3</b> Québec potato data set</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#selection-of-useful-variables"><i class="fa fa-check"></i><b>1.4</b> Selection of useful variables</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#arranging-the-data-frame"><i class="fa fa-check"></i><b>1.5</b> Arranging the data frame</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#cultivar-classes-correction"><i class="fa fa-check"></i><b>1.6</b> Cultivar classes correction</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#summarise-and-backup"><i class="fa fa-check"></i><b>1.7</b> Summarise and backup</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html"><i class="fa fa-check"></i><b>2</b> Cluster analysis of potato cultivars</a><ul>
<li class="chapter" data-level="2.1" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#objective"><i class="fa fa-check"></i><b>2.1</b> Objective</a></li>
<li class="chapter" data-level="2.2" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#useful-libraries-and-custom-functions"><i class="fa fa-check"></i><b>2.2</b> Useful libraries and custom functions</a></li>
<li class="chapter" data-level="2.3" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#leaves-processed-compositions-data-set"><i class="fa fa-check"></i><b>2.3</b> Leaves processed compositions data set</a></li>
<li class="chapter" data-level="2.4" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#high-yielders-delimiter"><i class="fa fa-check"></i><b>2.4</b> High yielders delimiter</a></li>
<li class="chapter" data-level="2.5" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#centered-log-ratio-clr-centroids-computation"><i class="fa fa-check"></i><b>2.5</b> Centered log-ratio (clr) centroids computation</a></li>
<li class="chapter" data-level="2.6" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#axis-reduction"><i class="fa fa-check"></i><b>2.6</b> Axis reduction</a></li>
<li class="chapter" data-level="2.7" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#cascade-k-means-clustering"><i class="fa fa-check"></i><b>2.7</b> Cascade K Means clustering</a></li>
<li class="chapter" data-level="2.8" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#arranging-data-for-machine-learning"><i class="fa fa-check"></i><b>2.8</b> Arranging data for Machine Learning</a></li>
<li class="chapter" data-level="2.9" data-path="Chapter-Clustering.html"><a href="Chapter-Clustering.html#clr-x-ionomics-groups-interactions-effects"><i class="fa fa-check"></i><b>2.9</b> clr x ionomics groups interactions effects</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html"><i class="fa fa-check"></i><b>3</b> Predicting tuber yield category</a><ul>
<li class="chapter" data-level="3.1" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#objective-1"><i class="fa fa-check"></i><b>3.1</b> Objective</a></li>
<li class="chapter" data-level="3.2" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#useful-libraries"><i class="fa fa-check"></i><b>3.2</b> Useful libraries</a></li>
<li class="chapter" data-level="3.3" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#machine-learning-data-set"><i class="fa fa-check"></i><b>3.3</b> Machine learning data set</a></li>
<li class="chapter" data-level="3.4" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#processing-machine-learning"><i class="fa fa-check"></i><b>3.4</b> Processing Machine learning</a><ul>
<li class="chapter" data-level="3.4.1" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#train-and-test-splits"><i class="fa fa-check"></i><b>3.4.1</b> Train and Test splits</a></li>
<li class="chapter" data-level="3.4.2" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#building-the-models"><i class="fa fa-check"></i><b>3.4.2</b> Building the Models</a></li>
<li class="chapter" data-level="3.4.3" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#goodness-of-fit-on-training-set"><i class="fa fa-check"></i><b>3.4.3</b> Goodness of fit on training set</a></li>
<li class="chapter" data-level="3.4.4" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#models-evaluation-on-testing-set"><i class="fa fa-check"></i><b>3.4.4</b> Models’ evaluation (on testing set)</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#yield-class-prediction-with-rf-algorithm-on-test-set"><i class="fa fa-check"></i><b>3.5</b> Yield Class Prediction with rf algorithm on test set</a></li>
<li class="chapter" data-level="3.6" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#comparison-with-non-informative-classification"><i class="fa fa-check"></i><b>3.6</b> Comparison with non-informative classification</a></li>
<li class="chapter" data-level="3.7" data-path="Chapter-Modeling.html"><a href="Chapter-Modeling.html#train-data-set-backup-for-tn-specimens-extraction"><i class="fa fa-check"></i><b>3.7</b> Train data set backup for TN specimens extraction</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="Chapter-Perturbation-vector.html"><a href="Chapter-Perturbation-vector.html"><i class="fa fa-check"></i><b>4</b> Perturbation vector theory</a><ul>
<li class="chapter" data-level="4.1" data-path="Chapter-Perturbation-vector.html"><a href="Chapter-Perturbation-vector.html#objective-2"><i class="fa fa-check"></i><b>4.1</b> Objective</a></li>
<li class="chapter" data-level="4.2" data-path="Chapter-Perturbation-vector.html"><a href="Chapter-Perturbation-vector.html#data-set-and-useful-libraries"><i class="fa fa-check"></i><b>4.2</b> Data set and useful libraries</a></li>
<li class="chapter" data-level="4.3" data-path="Chapter-Perturbation-vector.html"><a href="Chapter-Perturbation-vector.html#dissimilarity-index-between-compositions"><i class="fa fa-check"></i><b>4.3</b> Dissimilarity index between compositions</a></li>
<li class="chapter" data-level="4.4" data-path="Chapter-Perturbation-vector.html"><a href="Chapter-Perturbation-vector.html#rebalancing-a-misbalanced-sample-by-perturbation"><i class="fa fa-check"></i><b>4.4</b> Rebalancing a misbalanced sample by perturbation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Nutrient Diagnosis Of Potato</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="Chapter-Clustering" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Cluster analysis of potato cultivars</h1>
<div id="objective" class="section level2">
<h2><span class="header-section-number">2.1</span> Objective</h2>
<hr />
<p>The objective of this chapter is to assign cultivars to groups based on their leaf ionome. Although plant health is a continuous domain rather than a categorical status, yield thresholds are useful for decision-making. Because yield potential varies widely among cultivars, I split experimental data into low- and high-productivity categories using a marketable yield delimiter at the <span class="math inline">\(65^th\)</span> percentile for each cultivar. Hence, I use high yielders subpopulation (samples which marketable yield is larger than the yield cut-off) to perform a cascade k-means clustering aiming to discriminate Groups of similar multivariate compositions (<code>ionomics groups</code>). I combine a discriminant analysis to check the macroelements that best discriminate cultivars. I also check the performence of Groups discrimination by computing the <code>Groups x clr-coordinates</code> interaction effect coefficients in a linear mixed effect model. I finally append the new variable <code>ionomicGroup</code>to the leaves clr data frame and discard all the rows with any missing data. I map the experimental sites locations in the third sudsection of this chapter. The output data file is called <code>leaf_ml_df.csv</code> i.e., the data frame for machine learning chapter (Chapter <a href="Chapter-Modeling.html#Chapter-Modeling">3</a>).</p>
<hr />
</div>
<div id="useful-libraries-and-custom-functions" class="section level2">
<h2><span class="header-section-number">2.2</span> Useful libraries and custom functions</h2>
<p>A set of packages is needed for data handling and visualization like the <code>tidyverse</code> package presented in previous chapter (Chapter <a href="index.html#Chapter-Data-Processing">1</a>), <a href="https://rdrr.io/cran/ellipse/">ellipse</a> offers functions for drawing ellipses and ellipse-Like confidence regions (maybe I will set this option to FLASE for graph simplicity), <a href="https://rdrr.io/cran/mvoutlier/">mvoutlier</a> for multivariate outliers detection, <a href="http://pbil.univ-lyon1.fr/ADE-4">ade4</a> gathers tools for multivariate data analysis (I use it for discriminant analysis), <a href="https://rdrr.io/cran/vegan/">vegan</a> performs cluster analysis by k-means or cascade k-means clustering, <a href="https://github.com/dkahle/ggmap">ggmap</a> makes it easy to retrieve raster map tiles from online mapping services like Google Maps and Stamen Maps and plot them using the ggplot2 framework, <a href="https://www.r-pkg.org/pkg/extrafont">extrafont</a> for custom fonts for graphs with ggplot2, <a href="https://github.com/slowkow/ggrepel">ggrepel</a> provides text and label geoms for ‘ggplot2’ that help to avoid overlapping text labels, <a href="https://www.rdocumentation.org/packages/nlme">nlme</a> for linear and non-linear mixed effect modeling. Some custom functions are also loaded mainly for Pseudo r-square caculation with linear mixed effect model and discriminant biplot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)
<span class="kw">library</span>(<span class="st">&#39;ellipse&#39;</span>)
<span class="kw">library</span>(<span class="st">&quot;mvoutlier&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;ade4&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;vegan&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;extrafont&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;ggrepel&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;ggmap&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;nlme&quot;</span>)
<span class="kw">source</span>(<span class="st">&quot;data/functions.R&quot;</span>)
<span class="kw">source</span>(<span class="st">&#39;https://raw.githubusercontent.com/essicolo/AgFun/master/plotDA_trad.R&#39;</span>)</code></pre></div>
</div>
<div id="leaves-processed-compositions-data-set" class="section level2">
<h2><span class="header-section-number">2.3</span> Leaves processed compositions data set</h2>
<p>For this chapter, the initial data set is the outcome of the previous chapter (Chapter <a href="index.html#Chapter-Data-Processing">1</a>) <code>leaf_clust_df.csv</code>. I load the data frame and create vectors for useful columns selection.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">leaf_clust_df &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;output/leaf_clust_df.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   NoEssai = col_double(),
##   NoBloc = col_double(),
##   NoTraitement = col_double(),
##   Annee = col_double(),
##   LatDD = col_double(),
##   LonDD = col_double(),
##   AnalyseFoliaireStade = col_character(),
##   Cultivar = col_character(),
##   Maturity5 = col_character(),
##   RendVendable = col_double(),
##   leaf_countNA = col_double(),
##   clr_N = col_double(),
##   clr_P = col_double(),
##   clr_K = col_double(),
##   clr_Ca = col_double(),
##   clr_Mg = col_double(),
##   clr_Fv = col_double()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">keys_col &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;NoEssai&#39;</span>, <span class="st">&#39;NoBloc&#39;</span>, <span class="st">&#39;NoTraitement&#39;</span>)
clr_no &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;clr_N&quot;</span>, <span class="st">&quot;clr_P&quot;</span>, <span class="st">&quot;clr_K&quot;</span>, <span class="st">&quot;clr_Mg&quot;</span>, <span class="st">&quot;clr_Ca&quot;</span>, <span class="st">&quot;clr_Fv&quot;</span>)
cultivarAndyield &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Cultivar&#39;</span>, <span class="st">&#39;Maturity5&#39;</span>, <span class="st">&#39;RendVendable&#39;</span>)
extra_col &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;LatDD&#39;</span>, <span class="st">&#39;LonDD&#39;</span>, <span class="st">&#39;AnalyseFoliaireStade&#39;</span>)</code></pre></div>
<p>The next cell maps experimental sites locations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">qc_leaf &lt;-<span class="st"> </span><span class="kw">get_stamenmap</span>(<span class="dt">bbox =</span> <span class="kw">c</span>(<span class="dt">left =</span> <span class="op">-</span><span class="dv">76</span>, <span class="dt">right =</span> <span class="op">-</span><span class="dv">68</span>, <span class="dt">bottom =</span> <span class="dv">45</span>, <span class="dt">top =</span> <span class="dv">50</span>), 
                        <span class="dt">zoom =</span> <span class="dv">7</span>, <span class="dt">maptype =</span> <span class="st">&#39;toner-lite&#39;</span>)
<span class="kw">ggmap</span>(qc_leaf) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> leaf_clust_df <span class="op">%&gt;%</span>
<span class="st">               </span><span class="kw">select</span>(LonDD, LatDD) <span class="op">%&gt;%</span>
<span class="st">               </span><span class="kw">unique</span>(), <span class="kw">aes</span>(<span class="dt">x =</span> LonDD, <span class="dt">y =</span> LatDD),
             <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">coord_map</span>(<span class="st">&quot;mercator&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">family =</span> <span class="st">&quot;Arial&quot;</span>, <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">size =</span> <span class="dv">12</span>))</code></pre></div>
<div class="figure" style="text-align: center">
<img src="2019_Bookdown_files/figure-html/leaf_df-sites-locations-1.png" alt="Location of experimental sites (green dots) in the Québec potato data set." width="100%" />
<p class="caption">
(#fig:leaf_df-sites-locations)Location of experimental sites (green dots) in the Québec potato data set.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#ggsave(&quot;images/leaf_clust_df-sites-locations.png&quot;, width=10, height=8)</span></code></pre></div>
</div>
<div id="high-yielders-delimiter" class="section level2">
<h2><span class="header-section-number">2.4</span> High yielders delimiter</h2>
<p>For cluster analysis, I keep only high yielders i.e. yield 65% quantile cutter for each cultivar. The <code>cutQ</code> table contains the yield delimiter for each cultivar. Then, this table is used to add the variable <code>yieldClass</code> to <code>leaf_clust_df</code>. <code>HY</code> and <code>LY</code> stand for high yield and low yield respectively.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cutQ &lt;-<span class="st"> </span>leaf_clust_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Cultivar) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(RendVendable) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_if</span>(is.numeric, quantile, <span class="dt">probs=</span><span class="fl">0.65</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">rv_cut =</span> RendVendable)</code></pre></div>
<pre><code>## Adding missing grouping variables: `Cultivar`</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">leaf_clust_df &lt;-<span class="st"> </span>leaf_clust_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(cutQ, <span class="dt">by =</span> <span class="st">&quot;Cultivar&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">yieldClass =</span> forcats<span class="op">::</span><span class="kw">fct_relevel</span>(<span class="kw">ifelse</span>(RendVendable <span class="op">&gt;=</span><span class="st"> </span>rv_cut, <span class="st">&quot;HY&quot;</span>, <span class="st">&quot;LY&quot;</span>), <span class="st">&quot;LY&quot;</span>))</code></pre></div>
<p>For sake of verification, I compute average yield per yieldClass.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">meanYield =<span class="st"> </span>leaf_clust_df <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">group_by</span>(yieldClass) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(RendVendable) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">summarise_if</span>(is.numeric, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Adding missing grouping variables: `yieldClass`</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">meanYield</code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   yieldClass RendVendable
##   &lt;fct&gt;             &lt;dbl&gt;
## 1 LY                 25.8
## 2 HY                 40.5
## 3 &lt;NA&gt;              NaN</code></pre>
<p>So, the average marketable yield is 40.48 Mg <span class="math inline">\(ha^-1\)</span> for high yielders and 24.78 Mg <span class="math inline">\(ha^-1\)</span> for low yielders. In comparison, average potato tuber yields in 2017 in Canada and in Québec were respectively 40 Mg <span class="math inline">\(ha^-1\)</span> and 38.4 Mg <span class="math inline">\(ha^-1\)</span>.</p>
</div>
<div id="centered-log-ratio-clr-centroids-computation" class="section level2">
<h2><span class="header-section-number">2.5</span> Centered log-ratio (clr) centroids computation</h2>
<p>Compositional data transformation is done in the loaded file. I keep only clr-transformed coordinates for high yielders, at 10 % blossom (AnalyseFoliaireStade = 10% fleur) in the next chunk.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highYielders_df &lt;-<span class="st"> </span>leaf_clust_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">isNA =</span> <span class="kw">apply</span>(.[<span class="kw">c</span>(clr_no, cultivarAndyield)], <span class="dv">1</span>, anyNA)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">is10pcf =</span> AnalyseFoliaireStade <span class="op">==</span><span class="st"> &quot;10% fleur&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span>isNA <span class="op">&amp;</span><span class="st"> </span>is10pcf <span class="op">&amp;</span><span class="st"> </span>yieldClass <span class="op">==</span><span class="st"> &quot;HY&quot;</span> <span class="op">&amp;</span><span class="st"> </span>NoEssai <span class="op">!=</span><span class="st"> &quot;2&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="kw">one_of</span>(keys_col, clr_no, cultivarAndyield)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">droplevels</span>()
<span class="kw">nrow</span>(highYielders_df)</code></pre></div>
<pre><code>## [1] 1334</code></pre>
<p>So, 1334 lines of observations (samples) will be used to cluster potato cultivars. I check the number of samples per cultivar in this high yielders data set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">percentage &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">with</span>(highYielders_df, <span class="kw">prop.table</span>(<span class="kw">table</span>(Cultivar)) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>), <span class="dv">2</span>)
distribution &lt;-<span class="st"> </span><span class="kw">with</span>(highYielders_df, <span class="kw">cbind</span>(<span class="dt">numHY =</span> <span class="kw">table</span>(Cultivar), <span class="dt">percentage =</span> percentage))
distribution &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">cbind</span>(distribution, <span class="kw">rownames</span>(distribution)))
<span class="kw">colnames</span>(distribution)[<span class="dv">3</span>] &lt;-<span class="st"> &quot;Cultivar&quot;</span>
distribution<span class="op">$</span>numHY &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">as.character</span>(distribution<span class="op">$</span>numHY)) <span class="co"># numHY = number of samples</span>
distribution<span class="op">$</span>percentage &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">as.character</span>(distribution<span class="op">$</span>percentage))
distribution <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(numHY)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>(<span class="dv">5</span>) <span class="co"># arrange in descending order</span></code></pre></div>
<pre><code>##   numHY percentage  Cultivar
## 1   199      14.92  Superior
## 2   197      14.77  Goldrush
## 3   127       9.52   FL 1207
## 4   119       8.92 Chieftain
## 5    88       6.60  Atlantic</code></pre>
<div class="figure" style="text-align: center"><span id="fig:HY-cultivar-abundance"></span>
<img src="2019_Bookdown_files/figure-html/HY-cultivar-abundance-1.png" alt="High yielders cultivars abundance." width="100%" />
<p class="caption">
Figure 2.1: High yielders cultivars abundance.
</p>
</div>
<p>Some cultivars are well represented, like Superior and Goldrush. Let’s compute number of cultivars and trials in the data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data.frame</span>(<span class="dt">numb_cultivars =</span> <span class="kw">n_distinct</span>(highYielders_df<span class="op">$</span>Cultivar, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),
           <span class="dt">numb_trials =</span> <span class="kw">n_distinct</span>(highYielders_df<span class="op">$</span>NoEssai, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</code></pre></div>
<pre><code>##   numb_cultivars numb_trials
## 1             47         151</code></pre>
<p>I create a table with cultivars, maturity classes and compute median clr values i.e., clr centroids.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highYielders_clr &lt;-<span class="st"> </span>highYielders_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Cultivar, Maturity5) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Cultivar, Maturity5, <span class="kw">starts_with</span>(<span class="st">&quot;clr&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">list</span>(median))
highYielders_clr</code></pre></div>
<pre><code>## # A tibble: 47 x 8
## # Groups:   Cultivar [47]
##    Cultivar    Maturity5        clr_N clr_P clr_K clr_Mg clr_Ca clr_Fv
##    &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 AC Belmont  early            0.701 -2.02 0.664  -1.64 -1.11    3.47
##  2 AC Chaleur  early            0.696 -1.97 0.349  -1.54 -1.04    3.51
##  3 Amandine    mid-season       0.519 -2.29 0.557  -1.62 -0.696   3.53
##  4 Ambra       mid-season       0.713 -1.98 0.275  -1.39 -1.08    3.46
##  5 Andover     early mid-season 0.872 -2.17 0.738  -2.28 -0.808   3.57
##  6 Aquilon     mid-season       0.783 -1.86 0.387  -1.83 -0.901   3.48
##  7 Argos       late             0.767 -1.77 0.570  -1.70 -1.28    3.43
##  8 Atlantic    mid-season       0.784 -1.87 0.155  -1.50 -1.09    3.56
##  9 Bijou Rouge early            0.942 -1.93 0.563  -1.93 -1.12    3.61
## 10 Carolina    early            0.598 -2.19 0.131  -1.34 -0.837   3.63
## # ... with 37 more rows</code></pre>
<p>I use multivariate outliers detection technic to identify outliers with a criterion of detection limit of 0.975 by cultivar only if cultivars contain at leat 20 rows. If less than 20 rows, all rows are kept. The new data frame will be used for discriminant analysis. I call it <code>lda_df</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highYielders_df_IO &lt;-<span class="st"> </span>highYielders_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Cultivar) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;clr&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>({
    <span class="cf">if</span> (<span class="kw">nrow</span>(.) <span class="op">&lt;</span><span class="st"> </span><span class="dv">20</span>) {
      IO =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>, <span class="kw">nrow</span>(.))
    } <span class="cf">else</span> {
      IO =<span class="st"> </span><span class="kw">sign1</span>(.[,<span class="op">-</span><span class="dv">1</span>], <span class="dt">qcrit=</span><span class="fl">0.975</span>)<span class="op">$</span>wfinal01
    }
    <span class="kw">cbind</span>(.,IO)
  })

lda_df &lt;-<span class="st"> </span>highYielders_df_IO <span class="op">%&gt;%</span>
<span class="st">              </span><span class="kw">filter</span>(IO <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">              </span><span class="kw">droplevels</span>()
<span class="kw">nrow</span>(lda_df)</code></pre></div>
<pre><code>## [1] 1190</code></pre>
<p>So, 144 outliers have been discarded from the analysis.</p>
</div>
<div id="axis-reduction" class="section level2">
<h2><span class="header-section-number">2.6</span> Axis reduction</h2>
<p>Leaves composition data are compositionnal data (non-negative and summing to unity) so are multivariate. As argued by <a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a> it is not possible to draw such a diagram on paper with more than two or eventually three dimensions, however, even though it is a perfectly valid mathematical construct. For the purpose of analysis, I will project the multidimensional scatter diagram onto bivariate graph which axes are known to be of particular interest. The axes of this graph are chosen to represent a large fraction of the variability of the multidimensional <code>N-P-K-Mg-Ca-Fv</code> data matrix, in a space with reduced (i.e. lower) dimensionality relative to the original data set. With the next chunks, I perform a duality diagram (or <a href="http://pbil.univ-lyon1.fr/ade4/ade4-html/dudi.html">dudi</a>) PCA (priciple component analysis) and store scores and loadings. I also filter the data frame so that cultivars with less than 5 occurences will be masked on the resulting biplot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca_leaf &lt;-<span class="st"> </span><span class="kw">dudi.pca</span>(lda_df[clr_no], <span class="dt">scannf =</span> <span class="ot">FALSE</span>, <span class="dt">scale =</span> <span class="ot">FALSE</span>)
lda_leaf &lt;-<span class="st"> </span><span class="kw">discrimin</span>(<span class="dt">dudi =</span> pca_leaf, <span class="dt">fac =</span> <span class="kw">factor</span>(lda_df<span class="op">$</span>Cultivar), <span class="dt">scannf =</span> <span class="ot">FALSE</span>)
lda_leaf_score =<span class="st"> </span>lda_leaf<span class="op">$</span>li
lda_leaf_loading =<span class="st"> </span>lda_leaf<span class="op">$</span>fa</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lda_df<span class="op">$</span>Cultivar &lt;-<span class="st"> </span><span class="kw">factor</span>(lda_df<span class="op">$</span>Cultivar)
lda_leaf_group &lt;-<span class="st"> </span>lda_df<span class="op">$</span>Cultivar
n_cultivar &lt;-<span class="st"> </span><span class="kw">table</span>(lda_df<span class="op">$</span>Cultivar)
<span class="co"># Do not schow Cultivars whose number of occurrences is &lt; 5</span>
n_filter &lt;-<span class="st"> </span>lda_leaf_group <span class="op">%in%</span><span class="st"> </span><span class="kw">names</span>(n_cultivar[n_cultivar <span class="op">&gt;=</span><span class="st"> </span><span class="dv">5</span>])
filter_cultivars &lt;-<span class="st"> </span><span class="kw">names</span>(n_cultivar[n_cultivar <span class="op">&gt;=</span><span class="st"> </span><span class="dv">5</span>])
lda_df_filter &lt;-<span class="st"> </span>lda_df[n_filter, ]</code></pre></div>
<p>I plot the the distance biplot as result of discriminant analysis. I use a custom function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot_lda</span>(<span class="dt">score =</span> lda_leaf_score[n_filter, ],
         <span class="dt">loading =</span> lda_leaf_loading[n_filter, ],
         <span class="dt">group =</span> lda_leaf_group[n_filter],
         <span class="dt">ell_dev =</span> <span class="ot">FALSE</span>, 
         <span class="dt">ell_err =</span> <span class="ot">FALSE</span>, <span class="co">#TRUE, </span>
         <span class="dt">scale_load =</span> <span class="fl">0.5</span>,
         <span class="dt">level =</span> <span class="fl">0.95</span>,
         <span class="dt">legend =</span> <span class="ot">FALSE</span>,
         <span class="dt">label =</span> <span class="ot">TRUE</span>,
         <span class="dt">transparency =</span> <span class="fl">0.3</span>, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="dv">3</span>),
         <span class="dt">points =</span> <span class="ot">FALSE</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:distance-biplot"></span>
<img src="2019_Bookdown_files/figure-html/distance-biplot-1.png" alt="Discriminant distance biplot of potato cultivars." width="100%" />
<p class="caption">
Figure 2.2: Discriminant distance biplot of potato cultivars.
</p>
</div>
<p>The first discriminant axis (<code>DS1</code>) is formed mainly by <code>Mg</code>, <code>K</code> and <code>N</code>. The second discriminant axis (<code>DS2</code>) is driven mainly by <code>Fv</code>, <code>K</code> and weakely <code>Ca</code>. The next subsection performs cluster analysis.</p>
</div>
<div id="cascade-k-means-clustering" class="section level2">
<h2><span class="header-section-number">2.7</span> Cascade K Means clustering</h2>
<p>What is cascade K Means Clustering? It is an <em>unsupervised learning algorithm</em> inspired by its similar <a href="https://www.r-bloggers.com/k-means-clustering-in-r/">K Means clustering</a>, both trying to cluster data based on their similarity. There is no outcome to be predicted. The algorithm just tries to find patterns in the data. In k means clustering, we have to specify the number of clusters we want the data to be grouped into. In cascade K means method, we give a minimum and a maximum number of cluster wanted. The algorithm randomly assigns each observation to a cluster, and finds the centroid of each cluster. Then, the algorithm iterates through two steps:</p>
<ol style="list-style-type: decimal">
<li>reassign data points to the cluster whose centroid is closest,</li>
<li>Calculate new centroid of each cluster.</li>
</ol>
<p>These two steps are repeated till the within cluster variation cannot be reduced any further. The within cluster variation is calculated as the sum of the euclidean distance between the data points and their respective cluster centroids.</p>
<p>I use the high yielders clr centroids of cultivars in a new data frame which is the same as <code>highYielders_clr</code> without maturity classes.The chunk also plots the process results.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highYieldersCentroids &lt;-<span class="st"> </span>highYielders_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Cultivar) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;clr&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">list</span>(median))
<span class="kw">set.seed</span>(<span class="dv">5773</span>)
highYieldersKmeans &lt;-<span class="st"> </span><span class="kw">cascadeKM</span>(highYieldersCentroids[, <span class="op">-</span><span class="dv">1</span>], 
                                <span class="dt">inf.gr =</span> <span class="dv">3</span>, <span class="dt">sup.gr =</span> <span class="dv">12</span>, <span class="dt">criterion =</span> <span class="st">&quot;ssi&quot;</span>)
<span class="kw">plot</span>(highYieldersKmeans) </code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:clustering"></span>
<img src="2019_Bookdown_files/figure-html/clustering-1.png" alt="K-means partitions comparison (calinski criterion)." width="100%" />
<p class="caption">
Figure 2.3: K-means partitions comparison (calinski criterion).
</p>
</div>
<p>The red dot of the right hand side graph shows that 10 groups is the optimal clustering partition number. However, their is another optimum at <code>6 groups</code>, which is a more manageable number of clusters. The next chunk checks the partitions data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highYieldersKmeans<span class="op">$</span>partition <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   3 groups 4 groups 5 groups 6 groups 7 groups 8 groups 9 groups 10 groups
## 1        2        4        1        1        6        6        8         8
## 2        1        2        3        4        3        3        4         4
## 3        3        1        5        5        4        6        3         5
## 4        1        2        3        4        3        3        9         6
## 5        2        4        4        6        7        1        1        10
## 6        2        4        1        1        6        8        8         8
##   11 groups 12 groups
## 1         9        10
## 2        10        11
## 3         9        12
## 4        10        11
## 5         6         1
## 6         7        10</code></pre>
<p>I consider <code>6 groups</code> established from clustering corresponding to the fourth column. I can use the reference of the column or its name <code>6 groups</code> directly. I add it up to the centroids data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highYieldersCentroids<span class="op">$</span>kgroup &lt;-<span class="st"> </span>highYieldersKmeans<span class="op">$</span>partition[, <span class="st">&quot;6 groups&quot;</span>]</code></pre></div>
<p>Then, I compute discriminant scores centroïdes for cultivar and plot cultivar groups in LDA space with a custom function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lda_centroids &lt;-<span class="st"> </span>lda_leaf_score <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">group =</span> lda_leaf_group) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">list</span>(mean))</code></pre></div>
<p>The plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot_lda</span>(<span class="dt">score=</span>lda_leaf_score[n_filter, ],
         <span class="dt">loading=</span>lda_leaf_loading[n_filter, ],
         <span class="dt">group =</span> lda_leaf_group[n_filter],
         <span class="dt">ell_dev=</span><span class="ot">FALSE</span>, 
         <span class="dt">ell_err=</span> <span class="ot">FALSE</span>, <span class="co">#TRUE, </span>
         <span class="dt">scale_load =</span> <span class="fl">0.4</span>,
         <span class="dt">level=</span><span class="fl">0.95</span>,
         <span class="dt">legend=</span><span class="ot">FALSE</span>,
         <span class="dt">label=</span><span class="ot">TRUE</span>,
         <span class="dt">transparency=</span><span class="fl">0.4</span>, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">2.5</span>, <span class="dv">2</span>), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">4</span>),
         <span class="dt">points=</span>F)
<span class="co"># colour dots for groups (or clusters)</span>
col =<span class="st"> </span><span class="kw">factor</span>(highYieldersCentroids[highYieldersCentroids<span class="op">$</span>Cultivar <span class="op">%in%</span><span class="st"> </span>filter_cultivars, <span class="st">&#39;kgroup&#39;</span>][[<span class="dv">1</span>]])

<span class="co"># remove the cultivar column</span>
<span class="kw">points</span>(lda_centroids[lda_centroids<span class="op">$</span>group <span class="op">%in%</span><span class="st"> </span>filter_cultivars, <span class="kw">c</span>(<span class="st">&#39;DS1&#39;</span>, <span class="st">&#39;DS2&#39;</span>)], 
       <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">col =</span> col, <span class="dt">cex =</span> <span class="fl">0.9</span>)

<span class="kw">legend</span>(<span class="fl">1.2</span>, <span class="dv">4</span>, 
       <span class="dt">legend =</span> <span class="kw">paste</span>(<span class="kw">rep</span>(<span class="st">&#39;cluster&#39;</span>, <span class="kw">nlevels</span>(col)), <span class="kw">as.numeric</span>(<span class="kw">levels</span>(col))), 
       <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">col =</span> <span class="kw">unique</span>(col), <span class="dt">cex =</span> <span class="fl">0.9</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:d-biplot-2"></span>
<img src="2019_Bookdown_files/figure-html/d-biplot-2-1.png" alt="Discriminant distance biplot of potato cultivars showing ionomics groups." width="100%" />
<p class="caption">
Figure 2.4: Discriminant distance biplot of potato cultivars showing ionomics groups.
</p>
</div>
<p>Only 5 clusters are ploted, the third one may be masked because its cultivars has been filtered out. It’s a bit difficult to colour cultivar name in the plot with the custom function. I use functions from package <code>ggrepel</code> instead. New intermediate data frames are created for this purpose.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cultivars_filtre &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Cultivar =</span> filter_cultivars, <span class="dt">i_group=</span>col)

df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
    <span class="dt">score =</span> lda_leaf_score[n_filter, ],
    <span class="dt">loadings =</span> lda_leaf_loading[n_filter,],
    <span class="dt">Cultivar =</span> lda_leaf_group[n_filter]
                )
df &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">left_join</span>(cultivars_filtre, <span class="dt">by=</span><span class="st">&quot;Cultivar&quot;</span>)</code></pre></div>
<pre><code>## Warning: Column `Cultivar` joining factors with different levels, coercing
## to character vector</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   score.DS1  score.DS2 loadings.DS1 loadings.DS2   Cultivar i_group
## 1 1.0195082 -1.0396310    1.8869686   -0.2708043 AC Belmont       1
## 2 0.5628494 -1.5511832   -0.1703613   -0.6042699 AC Belmont       1
## 3 0.6855382 -1.3872559    1.9812115   -2.4466775 AC Belmont       1
## 4 0.5320794 -0.7359631   -2.3505801   -1.3418007 AC Belmont       1
## 5 0.4012165 -1.1776198    0.2286922   -1.2752145 AC Belmont       1
## 6 0.3170583 -1.2271324   -1.5759308    5.9387669 AC Belmont       1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">centroids =<span class="st"> </span>lda_centroids[lda_centroids<span class="op">$</span>group <span class="op">%in%</span><span class="st"> </span>filter_cultivars, ]
<span class="kw">names</span>(centroids)[<span class="kw">match</span>(<span class="st">&quot;group&quot;</span>, <span class="kw">names</span>(centroids))] &lt;-<span class="st"> &quot;Cultivar&quot;</span>
centroids &lt;-<span class="st"> </span>centroids <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">left_join</span>(cultivars_filtre, <span class="dt">by=</span><span class="st">&quot;Cultivar&quot;</span>)
centroids <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   Cultivar      DS1     DS2 i_group
##   &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;fct&gt;  
## 1 AC Belmont  0.107 -1.04   1      
## 2 AC Chaleur -0.538 -0.109  4      
## 3 Andover     1.92  -0.0363 6      
## 4 Aquilon     0.218 -0.275  1      
## 5 Argos       0.145 -0.878  2      
## 6 Atlantic   -1.21   0.427  4</code></pre>
<p>The chunk below plots discriminant biplot with colours corresponding to ionomics groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(centroids, <span class="kw">aes</span>(DS1, DS2, <span class="dt">label =</span> Cultivar, <span class="dt">col=</span>i_group)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text_repel</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>(<span class="dt">base_size =</span> <span class="dv">12</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text=</span><span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">family=</span><span class="st">&quot;Arial&quot;</span>, <span class="dt">face=</span><span class="st">&quot;bold&quot;</span>, <span class="dt">size =</span> <span class="dv">12</span>))

<span class="co"># Add discriminant loadings using geom_segment() and arrow()</span>
x=<span class="dv">0</span>; y=<span class="dv">0</span>; labels =<span class="st"> </span><span class="kw">c</span>(clr_no, <span class="kw">rep</span>(<span class="ot">NA</span>, <span class="kw">nrow</span>(df)<span class="op">-</span><span class="kw">length</span>(clr_no)))
g <span class="op">+</span><span class="st"> </span><span class="kw">geom_segment</span>(<span class="dt">data=</span>df, <span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y, <span class="dt">xend =</span> x<span class="op">+</span>loadings.DS1, <span class="dt">yend =</span> y<span class="op">+</span>loadings.DS2), 
                 <span class="dt">arrow =</span> <span class="kw">arrow</span>(), <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;grey80&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="dt">data =</span> df, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> loadings.DS1, <span class="dt">y =</span> loadings.DS2, <span class="dt">label =</span> labels), 
              <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>), <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">axis.line =</span> <span class="kw">element_blank</span>())</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:gg-biplot"></span>
<img src="2019_Bookdown_files/figure-html/gg-biplot-1.png" alt="Discriminant biplot and cluster analysis of potato cultivars." width="100%" />
<p class="caption">
Figure 2.5: Discriminant biplot and cluster analysis of potato cultivars.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#ggsave(&quot;images/cultivar_clust.png&quot;, width=10, height=8, dpi = 300)</span></code></pre></div>
<p>The next one separate the discriminant biplot in two stackable plots for easy reading.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">g1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(centroids, <span class="kw">aes</span>(DS1, DS2, <span class="dt">label =</span> Cultivar, <span class="dt">colour=</span>i_group)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>, <span class="dt">linetype=</span><span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="dv">0</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>, <span class="dt">linetype=</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_label_repel</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">6.5</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">guides</span>(<span class="dt">colour=</span><span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">12</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">12</span>),
        <span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">family=</span><span class="st">&quot;Arial&quot;</span>, <span class="dt">face=</span><span class="st">&quot;bold&quot;</span>, <span class="dt">size=</span><span class="dv">12</span>))

g2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_segment</span>(<span class="dt">data=</span>df, <span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y, <span class="dt">xend=</span>x<span class="op">+</span>loadings.DS1, <span class="dt">yend=</span>y<span class="op">+</span>loadings.DS2), 
                 <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">color=</span><span class="st">&quot;grey50&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_label</span>(<span class="dt">data=</span>df, <span class="dt">mapping=</span><span class="kw">aes</span>(<span class="dt">x=</span>loadings.DS1, <span class="dt">y=</span>loadings.DS2, <span class="dt">label=</span>labels), 
             <span class="dt">size=</span><span class="dv">5</span>, <span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;grey50&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>, <span class="dt">linetype=</span><span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="dv">0</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>, <span class="dt">linetype=</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">6.5</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;DS1&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;DS2&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">12</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text=</span><span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>),
        <span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">family =</span> <span class="st">&quot;Arial&quot;</span>, <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">size =</span> <span class="dv">12</span>))
cowplot<span class="op">::</span><span class="kw">plot_grid</span>(g1, g2)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:grid-plot"></span>
<img src="2019_Bookdown_files/figure-html/grid-plot-1.png" alt="Grid plot of discriminant and cluster analyses of potato cultivars." width="100%" />
<p class="caption">
Figure 2.6: Grid plot of discriminant and cluster analyses of potato cultivars.
</p>
</div>
<p>I push cultivars yield cut-off (<code>yieldCutoff</code>) and ionomics groups (<code>ionomicGroup</code>) in the initial data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ionomicGroup &lt;-<span class="st"> </span><span class="kw">data.frame</span>(lda_centroids[, <span class="dv">1</span>], 
                           <span class="dt">ionomicGroup =</span> <span class="kw">factor</span>(highYieldersKmeans<span class="op">$</span>partition[, <span class="st">&quot;6 groups&quot;</span>]))
<span class="kw">colnames</span>(ionomicGroup)[<span class="kw">colnames</span>(ionomicGroup)<span class="op">==</span><span class="st">&quot;group&quot;</span>] &lt;-<span class="st"> &quot;Cultivar&quot;</span>
cutQ &lt;-<span class="st"> </span>cutQ[<span class="op">-</span><span class="dv">1</span>, ] <span class="co"># to discard missing cultivar names</span>
<span class="kw">colnames</span>(cutQ)[<span class="kw">which</span>(<span class="kw">names</span>(cutQ) <span class="op">==</span><span class="st"> &quot;rv_cut&quot;</span>)] &lt;-<span class="st"> &quot;yieldCutoff&quot;</span>
cutQ_ig &lt;-<span class="st"> </span>cutQ <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">left_join</span>(ionomicGroup, <span class="dt">by =</span> <span class="st">&quot;Cultivar&quot;</span>)

leaf_clust_df &lt;-<span class="st"> </span>leaf_clust_df <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">left_join</span>(<span class="dt">y =</span> cutQ_ig, <span class="dt">by =</span> <span class="st">&#39;Cultivar&#39;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>rv_cut)</code></pre></div>
</div>
<div id="arranging-data-for-machine-learning" class="section level2">
<h2><span class="header-section-number">2.8</span> Arranging data for Machine Learning</h2>
<p>I select useful columns for the next chapter (Chapter <a href="Chapter-Modeling.html#Chapter-Modeling">3</a>) and save the new table as <code>dfml.csv</code>. I conserved only <code>complete cases</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">new_col &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;yieldCutoff&#39;</span>, <span class="st">&#39;yieldClass&#39;</span>, <span class="st">&#39;ionomicGroup&#39;</span>)
dfml &lt;-<span class="st"> </span>leaf_clust_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="kw">one_of</span>(<span class="kw">c</span>(keys_col, clr_no, cultivarAndyield, new_col, <span class="st">&#39;AnalyseFoliaireStade&#39;</span>))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">isNA =</span> <span class="kw">apply</span>(.[<span class="kw">c</span>(clr_no, cultivarAndyield)], <span class="dv">1</span>, anyNA)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">is10pcf =</span> AnalyseFoliaireStade <span class="op">==</span><span class="st"> &quot;10% fleur&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span>isNA <span class="op">&amp;</span><span class="st"> </span>is10pcf <span class="op">&amp;</span><span class="st"> </span>NoEssai <span class="op">!=</span><span class="st"> &quot;2&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(AnalyseFoliaireStade, isNA, is10pcf)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">droplevels</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(.))
<span class="kw">nrow</span>(dfml)</code></pre></div>
<pre><code>## [1] 3382</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write_csv</span>(dfml, <span class="st">&quot;output/dfml.csv&quot;</span>)</code></pre></div>
<p>So, the Machine learning data table contains 3382 samples.</p>
</div>
<div id="clr-x-ionomics-groups-interactions-effects" class="section level2">
<h2><span class="header-section-number">2.9</span> clr x ionomics groups interactions effects</h2>
<p>I use a linear mixed effect model to assess the effect of clr coordinates on tubers marketable yield in the ionomics groups. This last subsection perfoms this analysis by extracting and ploting the interaction coefficients of the model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dfml<span class="op">$</span>Cultivar &lt;-<span class="st"> </span><span class="kw">factor</span>(dfml<span class="op">$</span>Cultivar)
dfml<span class="op">$</span>NoEssai &lt;-<span class="st"> </span><span class="kw">factor</span>(dfml<span class="op">$</span>NoEssai)
<span class="kw">colnames</span>(dfml)[<span class="kw">colnames</span>(dfml)<span class="op">==</span><span class="st">&quot;ionomicGroup&quot;</span>] &lt;-<span class="st"> &quot;group_i&quot;</span>
dfml<span class="op">$</span>group_i &lt;-<span class="st"> </span><span class="kw">factor</span>(dfml<span class="op">$</span>group_i)

clr_no &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;clr_N&quot;</span>, <span class="st">&quot;clr_P&quot;</span>, <span class="st">&quot;clr_K&quot;</span>, <span class="st">&quot;clr_Ca&quot;</span>, <span class="st">&quot;clr_Mg&quot;</span>, <span class="st">&quot;clr_Fv&quot;</span>)
clrNo &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;clrN&quot;</span>, <span class="st">&quot;clrP&quot;</span>, <span class="st">&quot;clrK&quot;</span>, <span class="st">&quot;clrCa&quot;</span>, <span class="st">&quot;clrMg&quot;</span>, <span class="st">&quot;clrFv&quot;</span>) <span class="co"># for plot</span>
<span class="kw">colnames</span>(dfml)[<span class="kw">which</span>(<span class="kw">names</span>(dfml) <span class="op">%in%</span><span class="st"> </span>clr_no)] &lt;-<span class="st"> </span>clrNo</code></pre></div>
<p>I scale clr coordinates before fitting the linear mixed model. I discard the filling value to deal with singularity problem.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dfml.sc &lt;-<span class="st"> </span>dfml  <span class="co"># copy</span>
dfml.sc[, clrNo] &lt;-<span class="st"> </span><span class="kw">apply</span>(dfml.sc[, clrNo], <span class="dv">2</span>, scale)
used_clr =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;clrN&quot;</span>, <span class="st">&quot;clrP&quot;</span>, <span class="st">&quot;clrK&quot;</span>, <span class="st">&quot;clrCa&quot;</span>, <span class="st">&quot;clrMg&quot;</span>) <span class="co"># without &quot;clr_Fv&quot;</span>

lmm &lt;-<span class="st"> </span><span class="kw">lme</span>(RendVendable <span class="op">~</span><span class="st"> </span>(clrN <span class="op">+</span><span class="st"> </span>clrP <span class="op">+</span><span class="st"> </span>clrK <span class="op">+</span><span class="st"> </span>clrCa <span class="op">+</span><span class="st"> </span>clrMg)<span class="op">:</span>group_i, 
            <span class="dt">data=</span>dfml.sc, 
            <span class="dt">random=</span> <span class="op">~</span><span class="dv">1</span><span class="op">|</span>NoEssai)

pseudoR2 =<span class="st"> </span><span class="kw">rsq</span>(dfml.sc<span class="op">$</span>RendVendable, <span class="kw">predict</span>(lmm))
pseudoR2</code></pre></div>
<pre><code>## [1] 0.734548</code></pre>
<p>The next code extracts the interactions coefficients of the model and their p-values (pv) matrix.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(pv &lt;-<span class="st"> </span><span class="kw">summary</span>(lmm)<span class="op">$</span>tTable[<span class="op">-</span><span class="dv">1</span>,])</code></pre></div>
<pre><code>##                     Value  Std.Error   DF    t-value      p-value
## clrN:group_i1   3.9357284  0.4714419 3151  8.3482789 1.023693e-16
## clrN:group_i2   4.5086936  0.7705283 3151  5.8514314 5.373701e-09
## clrN:group_i3   1.2133428  6.0172969 3151  0.2016425 8.402092e-01
## clrN:group_i4   8.9271126  0.7222684 3151 12.3598269 2.653734e-34
## clrN:group_i5   6.6805497  2.4020738 3151  2.7811591 5.448723e-03
## clrN:group_i6   1.6894317  1.2249221 3151  1.3792156 1.679262e-01
## clrP:group_i1   2.2643683  0.5273867 3151  4.2935637 1.811318e-05
## clrP:group_i2   4.4674134  1.1599644 3151  3.8513367 1.198119e-04
## clrP:group_i3   1.1989684  8.5344952 3151  0.1404850 8.882858e-01
## clrP:group_i4   8.5517624  0.9043168 3151  9.4566005 6.012951e-21
## clrP:group_i5   7.1928922  3.0334416 3151  2.3711985 1.779031e-02
## clrP:group_i6  -0.2036706  1.6023732 3151 -0.1271056 8.988649e-01
## clrK:group_i1   2.6720318  0.7392049 3151  3.6147379 3.053569e-04
## clrK:group_i2   3.2583760  1.2697025 3151  2.5662514 1.032625e-02
## clrK:group_i3   5.1482219  8.3905696 3151  0.6135724 5.395422e-01
## clrK:group_i4   8.9001224  0.9695084 3151  9.1800365 7.595482e-20
## clrK:group_i5   8.1488974  3.4344139 3151  2.3727185 1.771741e-02
## clrK:group_i6  -0.7143722  2.0991856 3151 -0.3403092 7.336464e-01
## clrCa:group_i1  4.9639842  0.6928157 3151  7.1649414 9.647259e-13
## clrCa:group_i2  3.9986183  1.1915629 3151  3.3557760 8.008014e-04
## clrCa:group_i3  4.1933847 14.5907159 3151  0.2874009 7.738243e-01
## clrCa:group_i4  9.7662342  0.9515139 3151 10.2638898 2.465437e-24
## clrCa:group_i5  9.2009961  2.7687837 3151  3.3231184 9.003389e-04
## clrCa:group_i6  0.3216120  1.8131550 3151  0.1773770 8.592237e-01
## clrMg:group_i1  1.6655205  0.4952557 3151  3.3629507 7.803491e-04
## clrMg:group_i2  1.7260687  1.1074917 3151  1.5585387 1.192060e-01
## clrMg:group_i3 -1.7218358  7.3771342 3151 -0.2334017 8.154646e-01
## clrMg:group_i4  7.5539671  0.9042983 3151  8.3534022 9.811546e-17
## clrMg:group_i5  8.0241505  3.0299413 3151  2.6482858 8.130450e-03
## clrMg:group_i6 -0.2282890  1.6968340 3151 -0.1345382 8.929856e-01</code></pre>
<p>Then, I extract their confident intervals, and process data for the plot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">interval &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">Estimate =</span> <span class="kw">intervals</span>(lmm)<span class="op">$</span>fixed[<span class="op">-</span><span class="dv">1</span>, <span class="dv">2</span>],
                    <span class="dt">LL =</span> <span class="kw">intervals</span>(lmm)<span class="op">$</span>fixed[<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>], 
                    <span class="dt">UL =</span> <span class="kw">intervals</span>(lmm)<span class="op">$</span>fixed[<span class="op">-</span><span class="dv">1</span>, <span class="dv">3</span>]) 

interval<span class="op">$</span>variable &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">&#39;NA&#39;</span>, <span class="kw">nrow</span>(interval))
interval<span class="op">$</span>variable &lt;-<span class="st"> </span><span class="kw">rownames</span>(<span class="kw">intervals</span>(lmm)<span class="op">$</span>fixed)[<span class="op">-</span><span class="dv">1</span>]
interval<span class="op">$</span>ionomic_group &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">paste</span>(<span class="st">&quot;group&quot;</span>, <span class="dv">1</span><span class="op">:</span><span class="kw">nlevels</span>(dfml<span class="op">$</span>group_i)), <span class="kw">length</span>(clrNo)<span class="op">-</span><span class="dv">1</span>)
interval<span class="op">$</span>used_clr &lt;-<span class="st"> </span><span class="kw">rep</span>(used_clr, <span class="dt">each =</span> <span class="kw">nlevels</span>(dfml<span class="op">$</span>group_i))

interval<span class="op">$</span>pvalue &lt;-<span class="st"> </span><span class="kw">round</span>(pv[,<span class="st">&quot;p-value&quot;</span>], <span class="dv">4</span>)
interval<span class="op">$</span>is_significant =<span class="st"> </span><span class="kw">ifelse</span>(interval<span class="op">$</span>pvalue <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>, <span class="st">&#39;P &lt; 0.05&#39;</span>, <span class="st">&#39;P &gt; 0.05&#39;</span>)
interval</code></pre></div>
<pre><code>## # A tibble: 30 x 8
##    Estimate      LL    UL variable ionomic_group used_clr pvalue
##       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;chr&gt;     &lt;dbl&gt;
##  1     3.94   3.01   4.86 clrN:gr~ group 1       clrN     0     
##  2     4.51   3.00   6.02 clrN:gr~ group 2       clrN     0     
##  3     1.21 -10.6   13.0  clrN:gr~ group 3       clrN     0.840 
##  4     8.93   7.51  10.3  clrN:gr~ group 4       clrN     0     
##  5     6.68   1.97  11.4  clrN:gr~ group 5       clrN     0.0054
##  6     1.69  -0.712  4.09 clrN:gr~ group 6       clrN     0.168 
##  7     2.26   1.23   3.30 clrP:gr~ group 1       clrP     0     
##  8     4.47   2.19   6.74 clrP:gr~ group 2       clrP     0.0001
##  9     1.20 -15.5   17.9  clrP:gr~ group 3       clrP     0.888 
## 10     8.55   6.78  10.3  clrP:gr~ group 4       clrP     0     
## # ... with 20 more rows, and 1 more variable: is_significant &lt;chr&gt;</code></pre>
<p>This cell plots the interaction coefficients and their confident intervals using ggplot2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gg &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> interval, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Estimate, <span class="dt">y =</span> used_clr)) <span class="op">+</span><span class="st"> </span><span class="co">#, color=is_significant)) +</span>
<span class="st">         </span><span class="kw">facet_grid</span>(ionomic_group <span class="op">~</span><span class="st"> </span>.) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">geom_segment</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> LL, <span class="dt">xend =</span> UL, <span class="dt">y =</span> used_clr, <span class="dt">yend =</span> used_clr)) <span class="op">+</span>
<span class="st">         </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">         </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Coefficient&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;&quot;</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">theme_bw</span>() <span class="op">+</span>
<span class="st">         </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">family =</span> <span class="st">&quot;Arial&quot;</span>, <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">size =</span> <span class="dv">12</span>))
gg <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.title =</span> <span class="kw">element_blank</span>())</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:coefficients"></span>
<img src="2019_Bookdown_files/figure-html/coefficients-1.png" alt="Effect of ionome perturbation on marketable yield as illustrated by a linear mixed effect model." width="100%" />
<p class="caption">
Figure 2.7: Effect of ionome perturbation on marketable yield as illustrated by a linear mixed effect model.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#ggsave(&quot;images/coef_lmm.tiff&quot;, width = 5, height = 7, dpi = 300)</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Chapter-Modeling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["2019_Bookdown.pdf", "2019_Bookdown.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
